services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mom_development
      POSTGRES_USER: mom
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mom -d mom_development"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
      - "50051:50051"
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USERNAME: mom
      DB_PASSWORD: password
      GRPC_HOST: 0.0.0.0
      GRPC_PORT: 50051
      SECRET_KEY_BASE: development_secret_key_base_change_in_production
    volumes:
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    command: ["./docker-entrypoint.sh"]

volumes:
  postgres_data:
  bundle_cache:
